### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-webapp#29]
Haddock can be used in different scenarios like the [examples](https://github.com/haddocking/haddock3/tree/main/examples) and [tutorials](https://www.bonvinlab.org/education). It would be nice if the web application gave an overview of scenarios.

When an user picks a scenario it would be great to show the workflow builder with everything already filled in.

The scenario could include some instructions how to use it on the users own data, for example which files to upload.

**Comment by sverhoeven** [comment]
Would be nice to have an scenario which was quick and gave multiple clusters to make the caprieval analyis report interesting.

**Comment by sverhoeven** [comment]
In #87 the protein-protein and antibody-antigen scenario pages where added.
![localhost_3000_scenarios_antibody-antigen](https://github.com/i-VRESSE/haddock3-webapp/assets/1713488/3c3e29ad-c89b-42d9-bb2f-7c09211b1361)

These pages should be made easier to use, for example by
* Picking chains from PDBs
* Make first molecule have chain A and second molecule have chain B
  * Could be done by calling the [PDBtools webservice ](https://wenmr.science.uu.nl/pdbtools/)
* Pick restraint residues from 3D viewer, 2D sequence and/or list of numbers.
* The *.tbl files should be generated from selected residues similar to Haddock2.4 web site.

@rvhonorato can you help with this?

**Comment by rvhonorato** [comment]
> Picking chains from PDBs
> The *.tbl files should be generated from selected residues similar to Haddock2.4 web site.

I'm using webassembly for this in wenmr


> Could be done by calling the [PDBtools webservice](https://wenmr.science.uu.nl/pdbtools/)


I'd rather stay away from pdb-tools as much as possible, it's a great cli tool but in my experience using it for anything except that is very troublesome, since the operations it do are quite trivial its simpler to re-write the ones we need. Also its web-service is not a restapi and has a custom interface which is quite tricky to interact with.


> Pick restraint residues from 3D viewer, 2D sequence and/or list of numbers.

The sequence render is useful, but not simple to do - in this case specifically people should already know what are the residues since they are one of the key information.

> Make first molecule have chain A and second molecule have chain B

In the new interface i'm moving away from behind-the-scenes magic and providing a dialog with options, since this unseen data editing causes much more problems than it solves.


---

These steps seems to be related to data pre-processing, I'd say its best to do it in haddock3 instead of here. It could recieve a parameter that triggers a specific pre-processing based on the scenario, what you think @amjjbonvin  @mgiulini ?

**Comment by mgiulini** [comment]
my opinions here are that:

- reading the chains is crucial. Borrowing the wenmr code could be the best solution.
- I would stick to the lists of residues to define the restraints. Of course giving also the possibility to upload the tbl file.
- I would indeed not care too much about chains A and B as long as they are read at upload time.
- about generating the unambig and ambig restraints, the haddock3 codebase has now all the scripts necessary to do this. once the data are read we can launch a python subprocess to generate the necessary things. Of course borrowing the wenmr code here is a (faster) possibility.

**Comment by sverhoeven** [comment]
I managed to generated ambig.tbl file with #91 and https://github.com/haddocking/haddock3/pull/841
This uses the new `haddock3-restraints webservice` command for the haddock3 specific tasks and [ngl](https://github.com/nglviewer/ngl) to parse the chains and residues.

**Comment by sverhoeven** [comment]
With #120 we cover the most common scenarios. Other scenarios will be done in dedicated issues.
